M48
; DRILL file {KiCad (5.99.0-12063-ga3441a969d)} date Mon Aug 23 19:33:37 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-08-23T19:33:37+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-12063-ga3441a969d)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X8.0Y30.0
X8.0Y8.0
X68.0Y30.0
X68.0Y8.0
T0
M30
